extends: airbnb
installedESLint: true
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
  node: true
  jest: true
rules:
  no-console: warn
  no-unused-vars: warn
  eol-last: off
  comma-dangle: off
  no-trailing-spaces: off
  max-len: off
  no-return-assign: off
  class-methods-use-this: off
  no-param-reassign: off
  no-plusplus: off
  react/prefer-stateless-function: warn
  react/self-closing-comp: warn
  react/jsx-filename-extension: off
  react/require-default-props: off
  react/forbid-prop-types: off
  react/prop-types: off
  react/no-danger: off
  # func-names: off